---
title: Appendix 3 - Example ectotherm models
author: "Urtzi Enriquez-Urzelai & Lumír Gvoždík"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: show
  pdf_document: default
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
knitr::opts_knit$set(root.dir = '/Volumes/sugandila/ThermHydroBehav/')
```

Introduction


### Parameters and running the model

```{r}
library(NicheMapR)
```

Set parameters and ...

```{r, eval=F}
##########################
# Physiology

## preferred temperatures
tpref <- read.table('./data/Gvozdik_Kristin_TP.txt', 
                    header=T, sep='\t')
m_tpref <- mean(tpref$MeanTp[tpref$Treatment == 'Food'])
lbt <- mean(tpref$LBTp[tpref$Treatment == 'Food'])
ubt <- mean(tpref$UBTp[tpref$Treatment == 'Food'])


## metabolic rates
mrs <- read.table('./data/Gvozdik_Kristin_AS.txt', 
                  header=T, sep='\t')
colnames(mrs) <- c('temp', 'sex', 'mass', 'smr', 'mmr', 'scope', 'fscope')
smr_model <- nls(smr ~ exp(a + b * temp), data = mrs, start = list(a = 0, b = 0))
```


```{r, eval=F}
##########################
# Ectotherm model

load('./results/micro_Jihlava.Rda') # load microclimate


# full sun (0% shade)
maxshades <- micro$minshade + 1 # increase a bit to avoid convergence problems
minshades <- micro$minshade
shdburrow <- 2
# # or deep shade (90% shade)
# maxshades <- micro$maxshade
# minshades <- micro$maxshade
# shdburrow <- 0

# movement restriction
maxdepth <- 10 # up to 2 m
# maxdepth <- 8 # up to 50 cm

# morphology
Ww_g <- 3.5
shape <- 3 
pct_wet <- 90

# Physiology
T_F_min <- 4
T_F_max <- ubt
T_pref <- m_tpref
T_B_min <- 4
T_RB_min <- 4
CT_max <- 36
CT_min <- -2

# general behaviour
burrow <- 1
diurn <- 0
nocturn <- 1
crepus <- 1
shade_seek <- 0

# set behavioral strategy
behav <- 1 # 1 = cold shelters; 2 = warm shelters; 3 = passive
bwater <- 1 # following moist shelters (0 = no, 1 = yes)


ecto <- ectotherm(burrowtmp = behav, burrowwtr = bwater,
                  Ww_g = Ww_g, shape = shape, burrow=burrow,
                  T_F_min = T_F_min, T_F_max = ubt, T_pref = m_tpref,
                  T_B_min = T_B_min, T_RB_min = T_RB_min,
                  CT_max = CT_max, CT_min = CT_min,
                  diurn = diurn, nocturn = nocturn, crepus = crepus, 
                  shade_seek = shade_seek, maxdepth = maxdepth,
                  pct_wet = pct_wet, 
                  maxshade=maxshades, minshade=minshades, shdburrow = shdburrow)

```

Models can be run in a loop as in the `2_ectotherm_model.R` script, with the different behavioral options [.....]. Once results are stored, they can be loaded to inspect them.

```{r}
load('./results/micro_Jihlava.Rda')

source('./code/aux_functions.R')
ecto_df_current_sun <- load_ectos(path = "./results", scenario = "cur", movement = "200cm", 
                                  shading = "sun", micro = micro)
```

```{r}
par(mfrow=c(2,1), mar=c(3,4,0.5,0.5))

for(i in levels(ecto_df_current_sun$model)){
  
  environ <- ecto_df_current_sun[ecto_df_current_sun$model == i,]
  metout <- data.frame(micro$metout)
  
  # append dates
  days <- rep(seq(1, length(unique(environ$DAY))), 24)
  days <- days[order(days)]
  dates <- days+metout$TIME/60/24-1 # dates for hourly output
  
  
  with(environ, plot(TC ~ dates, ylab = "", xlab="", col = 'black', ylim = c(-70, 38), type = "l", yaxt = 'n'))
  with(environ, points(ACT * 2 - 10 ~ dates, type = "l", pch = 16, col = "orange"))
  with(environ, points(DEP/4 - 15 ~ dates, type = "l", col = "brown"))
  abline(4, 0, lty = 2, col = 'blue') # T_F_min
  abline(20, 0, lty = 2, col = 'red') # T_F_max
  abline(-2, 0, col = 'blue') # CT_min
  abline(36, 0, col = 'red') # CT_max
  ytick<-seq(0, 40, by=5)
  axis(side=2, at=ytick, labels = TRUE, las = 2, cex.axis = .7)
  mtext(text = c('Active', 'Inactive'), side = 2, line = 1, at = c(-6, -10), cex = .7, las = 2)
  ytick<-seq(-6, -10, by=-4)
  axis(side=2, at=ytick, labels = FALSE)
  mtext(text = rev(seq(0, 200, 40)), side = 2, line = 1, at = seq(-65, -15, length.out=6), las = 2, cex = .7)
  ytick<-seq(-65, -15, length.out=6)
  axis(side=2, at=ytick, labels = FALSE)
  abline(h = -15, lty = 2, col = 'grey')
  mtext(text = c('body temperature (°C)', 'depth (cm)'), side = 2, line = 2.5, at = c(22, -40), cex = .7)
  text(15, c(20 + 1, 4 + 1), c('VTmax', 'VTmin'), col = c('red', 'blue'), cex = 0.75)
  text(15, c(36 + 1, -2 + 1), c('CTmax', 'CTmin'), col = c('red', 'blue'), cex = 0.75)
  
}

```


<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;"></div>


